name = "agrajag-ravendb-cloudflare"
pages_build_output_dir = "dist"
compatibility_date = "2024-04-30"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[vars]
DB_URLS = '["https://ravendb1.supple.systems"]'
DB_NAME = "test-cf"
